{% set name = "Sophus" %}
{% set version = "1.24.6" %}
{% set version_with_epoch = "1!" ~ version %}

package:
  name: {{ name|lower }}
  version: {{ version_with_epoch }}

source:
  url: https://github.com/strasdat/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3f3098bdac2c74d42a921dbfb0e5e4b23601739e35a1c1236c2807c399da960c
  patches:
    - 0001-support-eigen-5.patch

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
  host:
    - eigen >=3.4
    - eigen-abi-devel >=3.4

  run:
    - {{ pin_compatible('eigen', max_pin='x') }}

test:
  commands:
    - test -f ${PREFIX}/include/sophus/types.hpp                # [unix]
    - test -f ${PREFIX}/share/sophus/cmake/SophusTargets.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\include\\sophus\\types.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\sophus\\cmake\\SophusTargets.cmake exit 1  # [win]

about:
  home: https://github.com/strasdat/Sophus
  summary: C++ implementation of Lie Groups using Eigen
  description: |
    This is a c++ implementation of Lie groups commonly used for 2d and 3d
    geometric problems.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://strasdat.github.io/Sophus/
  dev_url: https://github.com/strasdat/Sophus

extra:
  recipe-maintainers:
    - versatran01
